#как отдавать фронт и куда проксировать API
server {
    #Nginx слушает порт 80 ВНУТРИ контейнера
    listen 80;

    server_name localhost;

    #папка, откуда отдавать статику
    root /usr/share/nginx/html;

    #какой файл отдавать, если запросили директорию
    index index.html;

    # правило всё, что не /api/ - отдаём как статику
    location / {
        # try_files - попробуй по очереди
        # $uri - файл с таким именем
        # $uri/ -  директорию
        # /index.html - если ничего не нашли
        try_files $uri $uri/ /index.html;
    }

    # правило всё, что /api/ - проксируем на backend
    location /api/ {
        # "backend" - имя сервиса из docker-compose.yml.
        # Docker сам резолвит его в IP контейнера с бэкендом.
        # 8080 - внутренний порт Spring Boot приложения.
        proxy_pass http://backend:8080;

        # заголовки, которые Nginx передаёт бэкенду:
        # Host - оригинальный хост запроса
        proxy_set_header Host $host;
        # X-Real-IP - настоящий IP клиента
        proxy_set_header X-Real-IP $remote_addr;
        # X-Forwarded-For - цепочка прокси, через которые прошёл запрос
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        # X-Forwarded-Proto - http или https
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}